# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/12I2ov8WzWtSz151l9L9DhleE_GzUxewc
"""

import pandas as pd

from google.colab import files
uploaded = files.upload()

df = pd.read_csv("funnel_events_sample.csv")

order = [
    "visited_site",
    "signup_started",
    "details_filled",
    "email_verified",
    "purchase_completed"
]

counts = (
    df.groupby("step")["user_id"]
      .nunique()
      .reindex(order)
)

result = pd.DataFrame({
    "Stage": counts.index,
    "Users": counts.values
})

result["Conversion Rate"] = (
    result["Users"] / result["Users"].shift(1)
) * 100

result.loc[0, "Conversion Rate"] = 100

result["Users Lost"] = result["Users"].shift(1) - result["Users"]

print(result)

result["Drop Off"] = result["Users"].shift(1) - result["Users"]

print(result)

